name: Deploy Bots
on:
  pull_request:
    branches: [main]
    types: [closed]
jobs:
  deploy-participation-bot:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - run: |
          gcloud compute ssh participation-bot --zone=us-central1-a --command="sudo rm -rf /app && sudo git clone https://github.com/The-Red-Legion/red-legion-bots /app && cd /app/bots && sudo pip3 install -r ../requirements.txt psycopg2-binary && export DISCORD_TOKEN=\$(gcloud secrets versions access latest --secret=discord-token) && export TEXT_CHANNEL_ID=855869041687003156 && export DATABASE_URL=${{ secrets.DATABASE_URL }} && nohup python3 participation_bot.py &"