---
- name: Create .env file
  template:
    src: templates/env.j2
    dest: "{{ app_dir }}/.env"
    mode: '0600'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Set PYTHONPATH environment variable
  lineinfile:
    path: /etc/environment
    line: "PYTHONPATH={{ app_dir }}:$PYTHONPATH"
    state: present
