---
# Stop systemd service first (if it exists)
- name: Check if systemd service exists
  stat:
    path: /etc/systemd/system/red-legion-bot.service
  register: systemd_service

- name: Stop systemd service
  systemd:
    name: red-legion-bot
    state: stopped
  when: systemd_service.stat.exists
  ignore_errors: true

# Stop any manual processes (legacy support)
- name: Kill any running bot processes
  shell: pkill -f "python.*participation_bot" || true
  ignore_errors: true

- name: Wait for processes to terminate
  pause:
    seconds: 3

- name: Force kill any remaining bot processes
  shell: pkill -9 -f "python.*participation_bot" || true
  ignore_errors: true

# Legacy PID file cleanup
- name: Check if bot PID file exists
  stat:
    path: "{{ app_dir }}/bot.pid"
  register: pid_file
  when: not ansible_check_mode

- name: Remove PID file
  file:
    path: "{{ app_dir }}/bot.pid"
    state: absent
  when: not ansible_check_mode
  ignore_errors: true
