---
- name: Check if bot PID file exists
  stat:
    path: "{{ app_dir }}/bot.pid"
  register: pid_file

- name: Stop existing bot process
  command: kill {{ lookup('file', app_dir + '/bot.pid') }}
  when: pid_file.stat.exists
  ignore_errors: true

- name: Wait for process to terminate
  pause:
    seconds: 5
  when: pid_file.stat.exists

- name: Force kill if still running
  command: kill -9 {{ lookup('file', app_dir + '/bot.pid') }}
  when: pid_file.stat.exists
  ignore_errors: true

- name: Remove PID file
  file:
    path: "{{ app_dir }}/bot.pid"
    state: absent
  ignore_errors: true
