name: Sleep/Wake Participation Bot
on:
  schedule:
    - cron: '0 7 * * *'  # 2 AM CST (7 AM UTC)
    - cron: '0 12 * * *' # 6 AM CST (12 PM UTC)
  workflow_dispatch: # Manual trigger

jobs:
  manage-instance:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Sleep Instance
        if: github.event.schedule == '0 7 * * *' || github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'sleep'
        run: |
          gcloud compute instances stop arccorp-compute --zone=us-central1-a --project=rl-prod-471116
      - name: Wake Instance
        if: github.event.schedule == '0 12 * * *' || github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'wake'
        run: |
          gcloud compute instances start arccorp-compute --zone=us-central1-a --project=rl-prod-471116