   name: Test Bots
   on:
     pull_request:
       branches: [main]
       types: [opened, synchronize, reopened]
   jobs:
     test:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v4
         - name: Set up Python
           uses: actions/setup-python@v5
           with:
             python-version: '3.9'
         - name: Install dependencies
           run: |
             python -m pip install --upgrade pip
             pip install -r requirements.txt ruff pytest pytest-mock psycopg2-binary
         - name: Run linting
           run: ruff check src/*.py --line-length 120
         - name: Run unit tests
           env:
             PYTHONPATH: .
             DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
             TEXT_CHANNEL_ID: ${{ secrets.TEXT_CHANNEL_ID }}
             DATABASE_URL: ${{ secrets.DATABASE_URL }}
           run: pytest tests/
