   name: Test Bots
   on:
     pull_request:
       branches: ['*']
       types: [opened, synchronize, reopened]
   jobs:
     test:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v4
         - name: Set up Python
           uses: actions/setup-python@v5
           with:
             python-version: '3.9'
         - name: Install dependencies
           run: |
             python -m pip install --upgrade pip
             pip install -r requirements.txt ruff pytest pytest-mock psycopg2-binary
         - name: Run linting
           run: ruff check bots/participation_bot.py --line-length 120
         - name: Run unit tests
           env:
             DISCORD_TOKEN: "dummy-token"
             TEXT_CHANNEL_ID: "855869041687003156"
             DATABASE_URL: "postgresql://dummy_user:dummy_password@localhost:5432/dummy_db"
           run: pytest tests/
